# Site settings
title: 周欢
SEOTitle: 周欢
header-img: img/header/bg3.jpg
email: 936429286@qq.com
description: "这里是周欢的个人网站，与你一起发现更大的世界！"
keyword: "周欢, 边城少年, zhouhuan, 周欢的个人博客, 周欢的个人网站, @周欢, 周欢的博客, zhouhuan blog, 博客, 个人网站, 互联网, Web, JavaScript, vue, react, node"
url: "https://zhou-huan.github.io"
baseurl: ""

future: true

RSS: false
# weibo_username:     eleven_nnn
# github_username:    zhou-huan
# twitter_username:   zhouhuan



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: zhouhuan

# Netease settings
# netease_comment: false

# 百度统计 id
baidu_tongji_id: d610ad952c080f6cd56db23eb371c508


# Sidebar settings
sidebar: true
sidebar-about-description: "我把每一位读者都当成是朋友，朋友们的指教和关怀，自然永远是欢迎的。"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# 友情链接
friends: [
    {
      title: "boltdoggy",
      href: "https://boltdoggy.com/"
    },
    {
      title: "yondmn",
      href: "http://yondmn.cn/"
    },
    {
      title: "智源",
      href: "https://maskblog.com/"
    }
]
